# Generated by Django 5.1.4 on 2025-01-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyDiary', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='user',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diary_entries', to='MyDiary.tag'),
        ),
        migrations.DeleteModel(
            name='DiaryEntryTag',
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
